name: CI

on:
  push:
  workflow_dispatch:

jobs:
  # scan_changes:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     norg: ${{ steps.filter.outputs.norg }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: dorny/paths-filter@v2
  #       id: filter
  #       with:
  #         filters: |
  #           norg:
  #             - '**/*.norg'

  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # needs:
    #   - scan_changes
    # if: ${{ needs.scan_changes.outputs.norg == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - name: Create output folder
        run: mkdir output
      - name: Convert .norg files to markdown
        uses: docker://pandoc/core:3
        with:
          args: >-
            index.norg
            --from=init.lua
            --to=gfm
            --output=output/index.md
            ${{ steps.files_list.outputs.norg }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
      #   run: |
      #     for file in *.norg; do
      #       pandoc "$file" --from=norg-pandoc/init.lua --to=gfm -o "${file%.norg}.md"
      #     done
      # - name: Push changes to wiki
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git clone https://github.com/${{ github.repository }}.wiki.git wiki
      #     cp *.md wiki/
      #     cd wiki
      #     git add .
      #     git commit -m "Update wiki"
      #     git push
