name: CI

on:
  push:
  workflow_dispatch:

jobs:
  # scan_changes:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     norg: ${{ steps.filter.outputs.norg }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: dorny/paths-filter@v2
  #       id: filter
  #       with:
  #         filters: |
  #           norg:
  #             - '**/*.norg'

  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # needs:
    #   - scan_changes
    # if: ${{ needs.scan_changes.outputs.norg == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - name: Create output folder
        run: mkdir output
      - name: Convert .norg files to markdown
        uses: docker://pandoc/core:3
        with:
          args: >-
            index.norg
            --from=init.lua
            --to=gfm
            --output=output/index.md
            ${{ steps.files_list.outputs.norg }}
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: Push changes to wiki
        run: |
          cp output/index.md wiki/
          cd wiki
          git add .
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./wiki
          commit_message: "chore(build): update index.md"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
